language: python
python:
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  #- "pypy"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - python melta/test/core/__init__.py
  - python melta/test/dynamic/__init__.py
  - python melta/test/transactions/__init__py
  - python melta/test/utils/__init__.py
